# Generated by Django 3.1.2 on 2020-10-04 02:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 2, 47, 3, 480405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='site',
            name='rss_site',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
