# Generated by Django 3.1.2 on 2020-10-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201004_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
